services:
  data-processing-cloud-functions:
    container_name: data_processing_cloud_functions
    build:
      context: .
    volumes:
      - ./:/app
      - /Users/williamlytle/workspaces/3030/data:/app/data
    ports:
      - 3001:8080
    env_file: .env
    restart: always
