name: Determine environment
description: Determine environment

inputs:
  target_env:
    description: "Optional forced env: STAGING or PRODUCTION"
    required: false

outputs:
  branch:
    value: ${{ steps.branch.outputs.branch }}
  environment:
    value: ${{ steps.env.outputs.environment }}

runs:
  using: "composite"
  steps:
    - name: Extract branch name
      id: branch
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

    - name: Determine environment
      id: env
      shell: bash
      run: |
        # If target_env was provided, use it
        if [[ -n "${{ inputs.target_env }}" ]]; then
          echo "environment=${{ inputs.target_env }}" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Otherwise infer from branch
        if [[ "${{ steps.branch.outputs.branch }}" == "main" ]]; then
          echo "environment=PRODUCTION" >> $GITHUB_OUTPUT
        else
          echo "environment=STAGING" >> $GITHUB_OUTPUT
        fi