version: "3.9" # optional since v1.27.0
services:
  cms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./types:/app/types
      - ./public:/app/public
      - ./database:/app/database
      - ./config:/app/config

  db:
    image: postgis/postgis:16-3.4
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
