/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import localazy from "@localazy/strapi-plugin/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiImportExport from "strapi-import-export/strapi-admin";
import configSync from "strapi-plugin-config-sync/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    localazy: localazy,
    documentation: documentation,
    "users-permissions": usersPermissions,
    "strapi-import-export": strapiImportExport,
    "config-sync": configSync,
  },
});
