# Use the official Python image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy source code
COPY main.py .

# Run the Python script when the container starts
CMD ["python", "main.py"]
