#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

cd ./frontend && yarn types && yarn lint --fix && yarn check-types && git add src/types/generated/

SCRIPT_DIR="$(pwd)"
CMS_ENV_FILE="$SCRIPT_DIR/../cms/.env"
if [ -f "$CMS_ENV_FILE" ] ; then
    echo "Exporting CMS config.."
    cd .. && cd ./cms && yarn config-sync export -y && git add config/sync/*
else
    echo "CMS env file does not exist, can't export config"
    echo "DEBUG: looking for env file in $CMS_ENV_FILE"
fi

# Check if there are changes in the data_processing cloud function directory
if git diff --cached --exit-code --quiet -- ../cloud_functions/data_processing/ ; then
    echo "No changes in data_processing directory"
else
    echo "Changes detected in data_processing directory, running pre-commit hook"
    cd ../cloud_functions/data_processing && poetry run ruff check --fix && poetry run ruff format . && git add .
fi